# Generated by Django 3.2 on 2021-04-22 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Компания')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('poster', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Постер')),
                ('created_at', models.SmallIntegerField(null=True, verbose_name='Год выпуска игры')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('videogameplay', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='Геймплей игры')),
                ('mostwaiting', models.BooleanField(default=False, verbose_name='Самые ожидаемые игры')),
                ('torrent_file', models.FileField(blank=True, upload_to='files/%Y/%m/%d/', verbose_name='Торрент файл')),
                ('oc', models.CharField(max_length=100, null=True, verbose_name='Операционная система')),
                ('processor', models.CharField(max_length=100, null=True, verbose_name='Процессор')),
                ('ozu', models.CharField(max_length=100, null=True, verbose_name='Оперативка')),
                ('videocart', models.CharField(max_length=100, null=True, verbose_name='Видеокарта')),
                ('placeondisk', models.CharField(max_length=100, null=True, verbose_name='Место на жёстком диске')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.category', verbose_name='Категория')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Игра')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.reviews', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='movie_game_shots/', verbose_name='Картинка')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Кадр из игры',
                'verbose_name_plural': 'Кадры из игры',
            },
        ),
    ]
