# Generated by Django 3.2.2 on 2021-05-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_pagehit_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagehit',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='viewers_count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.pagehit'),
            preserve_default=False,
        ),
    ]
