# Generated by Django 3.2.2 on 2021-05-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210507_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='viewers_count',
        ),
    ]
