# Generated by Django 3.2.2 on 2021-05-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_viewers_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageHit',
        ),
    ]
