# Generated by Django 3.2.2 on 2021-05-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
    ]
