# Generated by Django 3.2.2 on 2021-05-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='special_image',
            field=models.ImageField(blank=True, upload_to='special_game_photos/%Y/%m/%d/', verbose_name='Постер'),
        ),
    ]
