# Generated by Django 3.2.2 on 2021-05-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_special_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='special_image',
            field=models.ImageField(upload_to='special_game_photos/%Y/%m/%d/', verbose_name='Картинка в header'),
        ),
    ]
