# Generated by Django 3.2.2 on 2021-05-10 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0011_alter_game_special_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='likes',
            field=models.ManyToManyField(related_name='game_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
