# Generated by Django 3.2.2 on 2021-05-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_reviews_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='downloads_count',
        ),
        migrations.AlterField(
            model_name='game',
            name='oc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='game',
            name='ozu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Оперативка'),
        ),
        migrations.AlterField(
            model_name='game',
            name='placeondisk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место на жёстком диске'),
        ),
        migrations.AlterField(
            model_name='game',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='game',
            name='torrent_file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Торрент файл'),
        ),
        migrations.AlterField(
            model_name='game',
            name='videocart',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Видеокарта'),
        ),
    ]
