# Generated by Django 3.2.2 on 2021-05-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20210511_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_at',
        ),
        migrations.AddField(
            model_name='game',
            name='date_of_issue',
            field=models.DateTimeField(default='2020-01-01', verbose_name='Дата выпуска игры'),
            preserve_default=False,
        ),
    ]
