# Generated by Django 3.2.2 on 2021-05-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20210511_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_of_issue',
            field=models.DateField(verbose_name='Дата выпуска игры'),
        ),
    ]
