# Generated by Django 3.2.2 on 2021-05-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_game_date_of_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='torrent_file_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер торрент-файла'),
        ),
    ]
