# Generated by Django 3.2.2 on 2021-05-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_game_torrent_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='torrent_file',
        ),
        migrations.RemoveField(
            model_name='game',
            name='torrent_file_size',
        ),
        migrations.CreateModel(
            name='TorrentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torrent_file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Торрент файл')),
                ('torrent_file_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер торрент-файла')),
                ('repack_author', models.CharField(max_length=100, verbose_name='Репак от')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Игра')),
            ],
        ),
    ]
