# Generated by Django 3.2.2 on 2021-05-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20210513_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torrentfile',
            options={'verbose_name': 'Торрент файл', 'verbose_name_plural': 'Торрент файлы'},
        ),
    ]
