# Generated by Django 3.2.2 on 2021-05-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_torrentfile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentfile',
            name='repack_author',
            field=models.CharField(choices=[('IG', 'Igruha'), ('XB', 'Xatab'), ('MX', 'R.G.Механики'), ('SXS', 'SxS-Fenixx'), ('FR', 'R.G.Freedom'), ('SR', 'SEYTER')], max_length=100, verbose_name='Репак от'),
        ),
    ]
