# Generated by Django 3.2.2 on 2021-05-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_torrentfile_repack_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentfile',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
