# Generated by Django 3.2.2 on 2021-05-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_torrentfile_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentfile',
            name='torrent_file_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя торрент файла'),
        ),
    ]
