# Generated by Django 3.2.2 on 2021-05-14 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_rating_ratingstar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
