# Generated by Django 3.2.2 on 2021-05-14 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0029_usergamerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamers',
            field=models.ManyToManyField(related_name='games', through='game.UserGameRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
