# Generated by Django 3.2.2 on 2021-05-14 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='mostwaiting',
        ),
        migrations.RemoveField(
            model_name='game',
            name='oc',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ozu',
        ),
        migrations.RemoveField(
            model_name='game',
            name='placeondisk',
        ),
        migrations.RemoveField(
            model_name='game',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='game',
            name='videocart',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='game.Genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='game',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.company', verbose_name='Компания'),
        ),
        migrations.CreateModel(
            name='MinSysReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Операционная система')),
                ('processor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Процессор')),
                ('ozu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Оперативка')),
                ('videocart', models.CharField(blank=True, max_length=100, null=True, verbose_name='Видеокарта')),
                ('placeondisk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место на жёстком диске')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Мин. сис. требования',
                'verbose_name_plural': 'Мин. сис. требования',
            },
        ),
    ]
