# Generated by Django 3.2.2 on 2021-05-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_auto_20210515_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='interface_lang',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Язык интерфейса'),
        ),
        migrations.AlterField(
            model_name='game',
            name='voice_acting_lang',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Язык озвучки'),
        ),
    ]
