# Generated by Django 3.2.2 on 2021-05-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_auto_20210515_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='company',
        ),
        migrations.AddField(
            model_name='game',
            name='company',
            field=models.ManyToManyField(to='game.Company', verbose_name='Компания'),
        ),
    ]
