# Generated by Django 3.2.2 on 2021-05-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_auto_20210515_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='minsysreq',
            name='directx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DirectX'),
        ),
    ]
