# Generated by Django 3.2.2 on 2021-05-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_alter_torrentfile_repack_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentfile',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='torrentfile',
            name='repack_author',
            field=models.CharField(blank=True, choices=[('Igruha', 'Igruha'), ('Xatab', 'Xatab'), ('R.G.Механики', 'R.G.Механики'), ('SxS-Fenixx', 'SxS-Fenixx'), ('R.G.Freedom', 'R.G.Freedom'), ('SEYTER', 'SEYTER'), ('SeregA-Lus', 'SeregA-Lus'), ('qoob', 'qoob'), ('GOG', 'GOG'), ('RGL-Rip', 'RGL-Rip')], max_length=100, null=True, verbose_name='Репак от'),
        ),
        migrations.AlterField(
            model_name='torrentfile',
            name='torrent_file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя торрент файла'),
        ),
    ]
