# Generated by Django 3.2.2 on 2021-05-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_auto_20210515_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentfile',
            name='repack_author',
            field=models.CharField(blank=True, choices=[('Igruha', 'Igruha'), ('Xatab', 'Xatab'), ('R.G.Механики', 'R.G.Механики'), ('SxS-Fenixx', 'SxS-Fenixx'), ('R.G.Freedom', 'R.G.Freedom'), ('SEYTER', 'SEYTER'), ('SeregA-Lus', 'SeregA-Lus'), ('qoob', 'qoob'), ('GOG', 'GOG'), ('RGL-Rip', 'RGL-Rip'), ('Pioneer', 'Pioneer')], max_length=100, null=True, verbose_name='Репак от'),
        ),
    ]
