# Generated by Django 3.2.2 on 2021-05-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_alter_minsysreq_directx'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_category', to='game.category', verbose_name='Главная категория'),
        ),
        migrations.AddField(
            model_name='game',
            name='main_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_genre', to='game.genre', verbose_name='Главный жанр'),
        ),
    ]
