# Generated by Django 3.2.2 on 2021-05-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_torrentfile_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minsysreq',
            name='directx',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DirectX'),
        ),
    ]
